###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@12"
}

###
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkyMDA2OTY2fQ.YZi9HNa5lJh5SZHD9Z6BCwC7Nbp6-eoKPmcY7u6Hzqo

###
GET http://localhost:3000/states/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkyMDA2OTY2fQ.YZi9HNa5lJh5SZHD9Z6BCwC7Nbp6-eoKPmcY7u6Hzqo

###
POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkyMDA2OTY2fQ.YZi9HNa5lJh5SZHD9Z6BCwC7Nbp6-eoKPmcY7u6Hzqo
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
GET http://localhost:3000/districts/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkyMDA2OTY2fQ.YZi9HNa5lJh5SZHD9Z6BCwC7Nbp6-eoKPmcY7u6Hzqo

###
DELETE http://localhost:3000/districts/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkyMDA2OTY2fQ.YZi9HNa5lJh5SZHD9Z6BCwC7Nbp6-eoKPmcY7u6Hzqo

###
PUT http://localhost:3000/districts/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkyMDA2OTY2fQ.YZi9HNa5lJh5SZHD9Z6BCwC7Nbp6-eoKPmcY7u6Hzqo
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
GET http://localhost:3000/states/2/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkyMDA2OTY2fQ.YZi9HNa5lJh5SZHD9Z6BCwC7Nbp6-eoKPmcY7u6Hzqo
